env:
  RUBY_VERSION: 2.7

name: Continuous Integration
on: [push,pull_request]

jobs:
  test:
    name: Run bin/test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-blabla
          # key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bin/test

